job('MavenWrtJenkins'){
    description("This is my first maven project generated by DSL on ${new Date()}, this project is a small maven project hosted on github")
    scm{
        git("https://github.com/fr-neil/JenkinsForMaven.git")
    }
    triggers{
        scm('* * * * *')
    }
    steps{
        maven('clean package', 'pom.xml')
    }
    publishers{
        archiveArtifacts('**/*.jar')
    }
}